### PR TITLE
Kill child processes created by NodeWebkit Chromedriver

### PR DESCRIPTION
**Pull request by iamdenny**
All the children processes should be killed together.

### CODE REVIEW

**Comment by michalc** [comment]
Thanks for the pull request. I will have a look at this: but I have noticed that it doesn't quit before, so looks like a good patch.

However

- At the moment I'm not keen on removing the dependency from package.json. I'm more pro bumping the version to be able to use https://github.com/nwjs/npm-installer/ , which at the moment accepts a parameter in .npmrc to set a custom download location. Slightly awkward as it then needs a http server running I think, but I wonder if this could be changed in a future version. Essentially I think this launcher should just work without having to install nodewebkit separately, and if someone wants to optimize the install process by pre-loading the binary somewhere, that should be optional.

  In any case, this should be in a separate pull request, so can be discussed separately.

- I think the comment is far too verbose. Something like "Kill child processes created by NodeWebkit Chromedriver" I think is enough.

Thanks.

**Comment by mackwic** [comment]
I confirm the issue on the last version of karma-nodewebkit-launcher (0.0.11). I also confirm that this PR correctly kills the node-webkit subprocesses.

However, I am wondering if a `kill -9` all isn't a too brutal solution...

**Comment by michalc** [comment]
@mackwic and @iamdenny I'm still not able to reproduce the issue. Can you post 

- How you're determining the child subprocesses aren't exiting? (Is it just that karma doesn't exit, or something else?
- Version of Karma, and OS

Thanks.

**Comment by iamdenny** [comment]
I tested it on MacOS. and the Karma version is 0.12.31

here is my karma.config.js
```javascript
if (!process.env.NODEWEBKIT_BIN) {
    process.env.NODEWEBKIT_BIN = getNodewebkitPath();
}

module.exports = function(config) {
	config.set({

		// base path that will be used to resolve all patterns (eg. files, exclude)
		basePath: './',

		// frameworks to use
		// available frameworks: https://npmjs.org/browse/keyword/karma-adapter
		frameworks: ['mocha'],


		// list of files / patterns to load in the browser
		files: [
			'......',
			'test/**/*.js',
                         {pattern: 'test/**/*.png', watched: false, included: false, served: true},
		],


		// list of files to exclude
		exclude: [

		],


		// preprocess matching files before serving them to the browser
		// available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
		preprocessors: {
            'js/**/*.js': ['coverage']
		},


		// test results reporter to use
		// possible values: 'dots', 'progress'
		// available reporters: https://npmjs.org/browse/keyword/karma-reporter
		reporters: ['spec', 'coverage'],

        // coverage
        coverageReporter: {
            dir: '../coverage/studio/',
            reporters: [
                { type: 'html', subdir: 'report-html' },
                { type: 'text', subdir: '.', file: 'text.txt' },
                { type: 'text-summary',  subdir: '.', file: false}
            ],
            watermarks: {
                statements: [ 50, 75 ],
                functions: [ 50, 75 ],
                branches: [ 50, 75 ],
                lines: [ 50, 75 ]
            }
        },

		// web server port
		port: 9876,


		// enable / disable colors in the output (reporters and logs)
		colors: true,


		// level of logging
		// possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
		logLevel: config.LOG_INFO,


		// enable / disable watching file and executing tests whenever any file changes
		autoWatch: false,


		// start these browsers
		// available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
		browsers: ['nodewebkit'],

		customLaunchers: {
			'nodewebkit': {
				base: 'NodeWebkit',
				options: {
					"version": "test",
					"window": {
                        "show": false
					}
				}
			}
		},


		// Continuous Integration mode
		// if true, Karma captures browsers, runs the tests and exits
		singleRun: true
	});
};

/**
 * get nodewebkit path
 * @returns {String}
 */
function getNodewebkitPath () {
    var path;
    var which = require('which').sync;

    try {
        path = which('nodewebkit');
    } catch (e) {}
    if (!path) {
        try {
            path = which('nw');
        } catch (e) {}
    }

    return path;
}

```

The PR Code is only for linux and mac, not for window. so It need to be checked the OS before killing sub process.

**Comment by michalc** [comment]
@iamdenny Does the issue still occur if you don't set `process.env.NODEWEBKIT_BIN`, and just use the default path the launcher uses?

**Comment by mackwic** [comment]
> How you're determining the child subprocesses aren't exiting? (Is it just that karma doesn't exit, or something else?

The window is still here, even if karma has closed in the shell. Also, circle-ci build doesn't finished when it should (that's how I found the issue).

> Your Karma config

[here](https://gist.github.com/mackwic/da4f22263f604ac4e6de#file-karma-conf-js-L111), note that I also use the `NODEWEBKIT_BIN` environment variable, it's part of our build matrix (yeah yeah... native plugins and cross platform makes a very special kind of hell).
I will test with the default path.

> version of karma and OS

default Ubuntu of circle-ci (12.04) + osx 10.9, only seen on karma 0.0.11

**Comment by iamdenny** [comment]
@michalc 
```
if (!process.env.NODEWEBKIT_BIN) {
    process.env.NODEWEBKIT_BIN = getNodewebkitPath();
}
```
This code is for multi OS. our team has linux, mac, window OS. and we install nodewebkit as global.
so using getNodewebkitPath() is good for us.

Anyhow you don't have child process of chrome after karma test?

**Comment by michalc** [comment]
Closing due to inactivity (on my part perhaps). Feel free to submit a new PR if desired.

**Pull request closed without merging**
